In [1]:
import numpy as np

In [19]:
a=np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]],[[10,11,12,14],[1,2,3,4],[0,8,2,0]]])
print(a)

[[[ 1  2  3  4]
  [ 3  4  5  6]
  [ 5  6  7  8]]

 [[10 11 12 14]
  [ 1  2  3  4]
  [ 0  8  2  0]]]


In [27]:
#accessing the elements from the array a
a[0,0,4]

IndexError: index 4 is out of bounds for axis 2 with size 4

In [58]:
a.ndim

3

In [44]:
b=np.linspace(1,10,20).reshape(4,5)
b

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [75]:
c=np.array([[[1,2,3]],[[10,20,11],[1,2,3]]])
print(f"the shape is {c.shape}")

the shape is (2,)


C:\Users\Msc 1\AppData\Local\Temp\ipykernel_9636\1737966430.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[[1,2,3]],[[10,20,11],[1,2,3]]])


In [76]:
print(f"the size is {c.size}")

the size is 2


In [77]:
print(f"the dimension is {c.ndim}")

the dimension is 1


In [82]:
from math import *
a=inf
a

inf